### ISSUE TITLE
Azure scraper broken

### ISSUE THREAD

**Issue by berendt** [catalyst-cloud/catalystcloud-price-comparison#7]
Looks like something's changed on Azure's price side. Google and AWS works.

```
Traceback (most recent call last):
  File "cloud_price_comparison.py", line 381, in <module>
    catagory_section = azure_price_page.find_all(id=catagory)[1]
IndexError: list index out of range
```

**Comment by unexceptable** [comment]
This has been fixed (twice) since, but it an ongoing issue, and we will likely need to switch to using the Azure API, which appears to need an active accounts.

I'll close this for now, and will hopefully keep this scraper working for a while longer until we switch to having it pull from their APIs, with appropriate configs that people can plug in their own Azure, and likely Google API Keys.
